//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "blog_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub blog_title: String,
    #[sea_orm(column_type = "Text")]
    pub author: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub image: Option<String>,
    pub tags: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub next: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub previous: Option<String>,
    pub date: DateTimeWithTimeZone,
    pub last_updated: DateTimeWithTimeZone,
    pub visible: bool,
    pub edited: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
